# Generated by Django 5.1.3 on 2025-01-04 12:10

import auth_user.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(validators=[auth_user.utils.check_otp_code], verbose_name='verification code')),
                ('type', models.CharField(choices=[('register', 'register'), ('reset_password', 'reset_password')], max_length=20, verbose_name='verification type')),
                ('expires_in', models.DateTimeField(verbose_name='expires in')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verification otp',
                'verbose_name_plural': 'verification otps',
                'ordering': ['-expires_in'],
            },
        ),
    ]
